### ISSUE TITLE
Desafio 3

### ISSUE THREAD

**Issue by naygo** [he4rt/he4rtoberfest-2022#129]
Opa pessoal, uma dúvida sobre o desafio 3 dos tipos de triângulo, talvez eu não tenha entendido direito.

A regra de não forma um triângulo é a seguinte: A ≥ B+C. No último exemplo eu tenho os valores 10.0 8.0 e 6.0, que ordenados em ordem decrescente, como pede no inicio, ficam:
A = 10.0
B = 8.0
C = 6.0

O último exemplo parece estar errado porque pede para mostrar a mensagem que não forma um triângulo, mas 10 >= 14 não é uma condição verdadeira.

**Comment by Luisnadachi** [comment]
Salve [naygo](https://github.com/naygo), seu ponto está correto, vou retirar o exemplo do readme para evitar confusões, obg pelo aviso.
