### ISSUE TITLE
Desafio 3

### ISSUE THREAD

**Issue by xandecoelho5** [he4rt/he4rtoberfest-2022#216]
Estava vendo o desafio 3, e vi que ele possui essas seguintes condições: 

* se A2 = B2 + C2, apresente a mensagem: TRIANGULO RETANGULO
* se A2 > B2 + C2, apresente a mensagem: TRIANGULO OBTUSANGULO
* se A2 < B2 + C2, apresente a mensagem: TRIANGULO ACUTANGULO

Tal que fica meio confuso para quem está lendo, sobre o que significa essas variáveis, A2, B2 e C2, tal que dá a entender que são variáveis.

Ao analisar o problema original, vi que era pra ser A², B² e C², de forma que o mal entendimento disso pode ocasionar no erro ao tentar resolver o problema.

Sugiro alterar para mostrar o valor com exponencial explícito, conforme a seguir:

* se A² = B² + C², apresente a mensagem: TRIANGULO RETANGULO
* se A² > B² + C², apresente a mensagem: TRIANGULO OBTUSANGULO
* se A² < B² + C², apresente a mensagem: TRIANGULO ACUTANGULO

**Comment by Luisnadachi** [comment]
Salve [xandecoelho5](https://github.com/xandecoelho5), você teria o link do problema original? So para eu dar uma olhada (não fui eu que escolheu os desafios), porque no me entendimento vi sendo A*2 = B*2 + C*2

**Comment by Rinyaresu** [comment]
https://www.beecrowd.com.br/repository/UOJ_1045_en.html

link do desafio original

**Comment by Luisnadachi** [comment]
Vlw [Rinyaresu](https://github.com/Rinyaresu), vou fazer então a correção aqui no readme sobre isso, obg [xandecoelho5](https://github.com/xandecoelho5) e [Rinyaresu](https://github.com/Rinyaresu), vou estar aceitando por enquanto os PRs que vierem como multiplicação de dobro por conta da troca repentina do enunciado do desafio.
