### ISSUE TITLE
Testes errados na tarefa #3

### ISSUE THREAD

**Issue by Camilotk** [he4rt/he4rtoberfest-2022#699]
Os testes do [exercício 3](https://github.com/he4rt/he4rtoberfest-2022/blob/main/challenges/3-tipos-de-triangulo/readme.md) tem erros como apresentados.

Meu código em Clojure não está batendo com o proposto nos testes, como exemplo a condição que `A = 5.0`, `B = 7.0` e `C = 2.0` deveria retornar `NAO FORMA TRIANGULO` porém: 

![image](https://user-images.githubusercontent.com/30880723/194670303-75a3c94c-6c4a-4207-bbfa-8bc8d54966b9.png)

E isso também é verdade para o código em Python aceito:

![image](https://user-images.githubusercontent.com/30880723/194670275-9bac8c19-99e9-4418-b926-f19fcc78fe8d.png)

E faz completo sentido já que a regra checada é $a\geq b+c$ e com esses inputs temos $5\geq 7+2$ que então $5\geq9$ que retorna `false` ao contrário do que está no README do desafio.

Ao mesmo tempo, a regra para acutângulo é $a^{2} < b^{2} + c^{2}$ que então fica $5^{2} < 7 ^ {2} + 2 ^ {2}$ ou seja $25 < 49 + 4$ que fica $25 < 53$ e retorna `true`.

Dos quatro testes apenas dois estão corretos, sendo que para as entradas `a = 6.0`, `b = 6.0` e `c = 10.0` também está com erro.

**Comment by edurevsky** [comment]
O erro acontece pois precisa da ordenação das entradas em ordem decrescente.

Por exemplo as entradas a = 5.0, b = 7.0 e c = 2.0 precisam ficar como: a = 7.0, b = 5.0 e c = 2.0.
