### ISSUE TITLE
Estrutura de pastas

### ISSUE THREAD

**Issue by marcosvag** [he4rt/he4rtoberfest-2022#754]
Pasta indevida no diretório `challenges/`:
![image](https://user-images.githubusercontent.com/101986630/194718125-905f22ae-020c-4a8d-a11e-fb359a614d37.png)

Pasta `TypeScript` duplicada no diretório `challenges/0-hello-world/`
![image](https://user-images.githubusercontent.com/101986630/194718375-f96a9f5c-e938-4c53-9cca-897b3281d9a1.png)

**Comment by Luisnadachi** [comment]
Já fiz o revert do PR das duas pastas, obg pelo aviso [marcosvag](https://github.com/marcosvag)
